const enum ClassList {
  mainContainer = 'main__container',
  banner = 'banner',
  // 404
  page404text = 'page-404__text',
  page404title = 'page-404__title',
  // Popup
  popup = 'popup',
  popupShow = 'popup_show',
  // Sign in
  signForm = 'sign-form',
  signIn = 'sign-form_sign-in',
  signUp = 'sign-form_sign-up',
  signTitle = 'sign-form__title',
  signInput = 'sign-form__input',
  signInputBox = 'sign-form__input-box',
  signLabel = 'sign-form__label',
  signLabelText = 'sign-form__label-text',
  signPassword = 'sign-password',
  bigO = 'sign-form__big-o',
  smallO = 'sign-form__small-o',
  signLink = 'sign-form__link',
  signInButton = 'sign-form__button',
  signInButtonText = 'sign-form__button-text',
  signInView = 'sign-in-view',
  signUpView = 'sign-up-view',
  inputError = 'sign-form__input-error',
  inputErrorActive = 'sign-form__input-error_active',
  // Plans
  planContainer = 'plan',
  weekLine = 'plan__week-line',
  weekTextContainer = 'plan__text-container',
  weekTextValue = 'plan__text-value',
  planBody = 'plan__body',
  planTools = 'plan__tools',
  planButtons = 'plan__buttons',
  planAddButton = 'plan__button-add',
  planAddButtonValue = 'plan__button-add-value',
  planRemoveZone = 'plan__remove',
  planDaysContainer = 'plan__days',
  planDay = 'plan__day',
  planDayLine = 'plan__day-line',
  planDayName = 'plan__day-name',
  planDayHours = 'plan__day-hours',
  planField = 'plan__field',
  planAddButtonName = 'plan__button-add-name',
  weekendFields = 'weekend-fields',
  weekendFieldsBig = 'weekend-fields__big',
  weekendFieldsSmall = 'weekend-fields__small',
  planRound = 'plan-round',
  planRoundBlur = 'plan-round__blur',
  planRoundVal = 'plan-round__value',
  // Editor
  editor = 'editor',
  editorTools = 'editor__tools',
  editorTitle = 'editor__title',
  editorText = 'editor__text',
  editorButton = 'editor__button',
  editorColorPicker = 'editor__color-picker',
  editorColorBox = 'editor__color-box',
  editorColorBoxActive = 'editor__color-box_active',
  editorColorRound = 'editor__color-round',
  editorSaveIcon = 'editor__save-icon',
  // time container
  timeContainer = 'time-container',
  timeContainerSlider = 'time-container__slider',
  timeContainerTimeInput = 'time-container__time-input',
  timeContainerTimeLabel = 'time-container__time-label',
}

export default ClassList;
