const enum ClassList {
  mainContainer = 'main__container',
  page404text = 'page-404__text',
  page404title = 'page-404__title',
  popup = 'popup',
  popupShow = 'popup_show',
  signForm = 'sign-form',
  signIn = 'sign-form_sign-in',
  signUp = 'sign-form_sign-up',
  signTitle = 'sign-form__title',
  signInput = 'sign-form__input',
  signInputBox = 'sign-form__input-box',
  signLabel = 'sign-form__label',
  signLabelText = 'sign-form__label-text',
  signPassword = 'sign-password',
  bigO = 'sign-form__big-o',
  smallO = 'sign-form__small-o',
  signLink = 'sign-form__link',
  signInButton = 'sign-form__button',
  signInButtonText = 'sign-form__button-text',
  signInView = 'sign-in-view',
  signUpView = 'sign-up-view',
  inputError = 'sign-form__input-error',
  inputErrorActive = 'sign-form__input-error_active',
}

export default ClassList;
