const enum InnerText {
  page404text = "Sorry, didn't find that page...",
  signIn = 'Sign In',
  signUp = 'Sign Up',
  rememberMe = 'Remember me',
  newAccount = 'I need a new account',
  iHaveAccount = 'I already have an account',
  allWeekHours = ' / 168 h',
  allDayHours = ' / 24 h',
  defaultPlanText = '- Make some awesome things',
  emptyPlanText = 'There are no plans at this time.',
  defaultPlanName = 'Plan for ...',
  hoursText = 'Hours',
  minutesText = 'Minutes',
  thoughtText = 'Thought',
  weekText = 'Week',
  emptyTitle = 'Free time',
  emptyText = '',
  timeOfDayAM = 'AM',
  timeOfDayPM = 'PM',
  perWeek = '(per week)',
  perDay = 'per day',
}

export default InnerText;
