import { Plan } from '../../../base/interface';

const testPlans: Plan[] = [
  {
    _id: '1',
    color: '#E6E6FA',
    title: 'Sleep',
    text: 'just sleep',
    duration: 2940,
  },
  {
    _id: '2',
    color: '#9F5454',
    title: 'Work',
    text: 'just work',
    duration: 2640,
  },
  {
    _id: '3',
    color: '#98FF98',
    title: 'Family',
    text: 'just family',
    duration: 2040,
  },
  {
    _id: '4',
    color: '#E6E6FA',
    title: 'Personal time',
    text: 'just reeding',
    duration: 570,
  },
  {
    _id: '5',
    color: '#FFE5B4',
    title: 'Dog',
    text: 'just reeding',
    duration: 420,
  },
  {
    _id: '6',
    color: '#4682B4',
    title: 'English',
    text: 'just reeding',
    duration: 210,
  },
  {
    _id: '7',
    color: '#FFD700',
    title: 'Reed',
    text: 'just reeding',
    duration: 140,
  },
  {
    _id: '8',
    color: '#D3D3D3',
    title: 'Road',
    text: 'just reeding',
    duration: 450,
  },
  {
    _id: '9',
    color: '#808000',
    title: 'Shopping',
    text: 'just reeding',
    duration: 180,
  },
  {
    _id: '10',
    color: '#FA8072',
    title: 'Yoga',
    text: 'just reeding',
    duration: 105,
  },
  {
    _id: '11',
    color: '#9DC183',
    title: 'Home routine',
    text: 'just reeding',
    duration: 210,
  },
  // {
  //   _id: '12',
  //   color: '#C8A2C8',
  //   title: 'personal time',
  //   text: 'just reeding',
  //   duration: 300,
  // },
  // {
  //   _id: '13',
  //   color: '#F5DEB3',
  //   title: 'personal time',
  //   text: 'just reeding',
  //   duration: 100,
  // },
  // {
  //   _id: '14',
  //   color: '#FFD700',
  //   title: 'personal time',
  //   text: 'just reeding',
  //   duration: 200,
  // },
  // {
  //   _id: '15',
  //   color: '#4682B4',
  //   title: 'personal time',
  //   text: 'just reeding',
  //   duration: 100,
  // },
  // {
  //   _id: '16',
  //   color: '#9370DB',
  //   title: 'personal time',
  //   text: 'just reeding',
  //   duration: 30,
  // },
  // {
  //   _id: '17',
  //   color: '#00FFFF',
  //   title: 'personal time',
  //   text: 'just reeding',
  //   duration: 300,
  // },
  // {
  //   _id: '18',
  //   color: '#800000',
  //   title: 'personal time',
  //   text: 'just reeding',
  //   duration: 400,
  // },
  // {
  //   _id: '19',
  //   color: '#A9A9A9',
  //   title: 'personal time',
  //   text: 'just reeding',
  //   duration: 100,
  // },
  // {
  //   _id: '20',
  //   color: '#FF1493',
  //   title: 'personal time',
  //   text: 'just reeding',
  //   duration: 60,
  // },
  // {
  //   _id: '21',
  //   color: '#F0E68C',
  //   title: 'personal time',
  //   text: 'just reeding',
  //   duration: 120,
  // },
  // {
  //   _id: '22',
  //   color: '#A020F0',
  //   title: 'personal time',
  //   text: 'just reeding',
  //   duration: 120,
  // },
  // {
  //   _id: '23',
  //   color: '#1E90FF',
  //   title: 'personal time',
  //   text: 'just reeding',
  //   duration: 600,
  // },
  // {
  //   _id: '24',
  //   color: '#90EE90',
  //   title: 'personal time',
  //   text: 'just reeding',
  //   duration: 30,
  // },
  // {
  //   _id: '25',
  //   color: '#FFA500',
  //   title: 'personal time',
  //   text: 'just reeding',
  //   duration: 30,
  // },
];

export default testPlans;
